#pragma once

// Cluster Config
#define CLUSTER_KEY_SIZE 32
#define MAX_NEIGHBORS 10
#define MAX_CLUSTER_SIZE 5
#define ELECTION_WINDOW_MS 10000
#define STATE_MACHINE_TASK_STACK_SIZE 4096
#define STATE_MACHINE_TASK_PRIORITY 5
#define METRICS_TASK_STACK_SIZE 4096
#define METRICS_TASK_PRIORITY 4

// Weights
#define WEIGHT_BATTERY 0.3f
#define WEIGHT_UPTIME 0.2f
#define WEIGHT_TRUST 0.3f
#define WEIGHT_LINK_QUALITY 0.2f
#define HSR_WEIGHT 0.4f
#define REPUTATION_WEIGHT 0.3f
#define PDR_WEIGHT 0.3f

// STELLAR
#define USE_STELLAR_ALGORITHM 1
#define ENTROPY_GAMMA 1.0f
#define EWMA_VARIANCE_ALPHA 0.1f
#define MIN_WEIGHT_VALUE 0.05f
#define LYAPUNOV_BETA 0.1f
#define LYAPUNOV_ETA 0.01f
#define LYAPUNOV_LAMBDA 0.01f
#define CONVERGENCE_THRESHOLD 0.001f
#define UTILITY_LAMBDA_B 2.0f
#define UTILITY_LAMBDA_U 1.0f
#define UTILITY_GAMMA_L 2.0f
#define UPTIME_MAX_DAYS 7.0f
#define PARETO_DELTA 0.1f
#define CENTRALITY_EPSILON 0.5f
#define DISAGREE_BATTERY 0.1f
#define DISAGREE_UPTIME 0.1f
#define DISAGREE_TRUST 0.1f
#define DISAGREE_LINKQ 0.1f
#define PDR_EWMA_ALPHA 0.1f
#define TRUST_FLOOR 0.2f
#define BATTERY_LOW_THRESHOLD 0.2f
#define LINK_QUALITY_FLOOR 0.2f

// ESP-NOW
#define ESP_NOW_CHANNEL 1
#define ESP_NOW_PMK "pmk1234567890123"
#define ESP_NOW_LMK "lmk1234567890123"

// Persistence
#define SPIFFS_BASE_PATH "/spiffs"
